---
- name: Configuração inicial do servidor
  hosts: all
  become: true

  tasks:
    - name: Atualizar os pacotes do sistema
      apt:
        update_cache: yes

    - name: Instalar pacotes necessários
      apt:
        name: 
          - apache2
          - curl
        state: present

    - name: Criar um diretório
      file:
        path: /var/www/html/custom
        state: directory
        mode: '0755'

    - name: Copiar um arquivo HTML de exemplo
      copy:
        content: "<html><body><h1>Site configurado pelo Ansible!</h1></body></html>"
        dest: /var/www/html/index.html
        mode: '0644'
